### PR TITLE
Fix test

### LINKED ISSUE #78: SinglePeersetSpec.should be able to execute transaction even if leader fails after first apply() FAILED
[test-reports.zip](https://github.com/Davenury/Unifying-Consensus-And-Atomic-Commitment-PoC/files/10102470/test-reports.zip)

### PR DESCRIPTION
**Pull request by Rados13**
Should fix #78

### CODE REVIEW

File: src/main/kotlin/com/github/davenury/ucac/commitment/gpac/GPACProtocol.kt [hunk 1]
```diff
@@ -471,7 +471,8 @@ class GPACProtocolImpl(
 
     private fun changeTimeout(change: Change, detailedMessage: String? = null) {
         val changeId = change.toHistoryEntry().getId()
-        changeIdToCompletableFuture[changeId]?.complete(ChangeResult(ChangeResult.Status.TIMEOUT, detailedMessage))
+        logger.info("Change timeout: $changeId, map: $changeIdToCompletableFuture")
```
Comment (kjarosh) [inline src/main/kotlin/com/github/davenury/ucac/commitment/gpac/GPACProtocol.kt:474]: Isn't it too much for INFO? Maybe DEBUG?

**Review by Davenury — DISMISSED** [review]

**Review by kjarosh — APPROVED** [review]
